/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package simori
import simori.domain.Mode
import simori.domain.SimoriState

fun main(args: Array<String>) {
    var m: Mode = Mode.SIMORI_ON_OFF
    if (m == Mode.SIMORI_ON_OFF) {
        print("ON/OFF Mode\n")
    }
    println("Hello World!")
}
