/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Simori_On_V2_Test

import kotlin.test.Test
import kotlin.test.assertNotNull

import Simori_On_V2.domain.SimoriState

class AppTest {
    @Test fun testAppHasAGreeting() {
    }
}
