/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Simori_On_V2

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "App should have a greeting")
    }
}
