package simori.domain

enum class Mode {
    SIMORI_ON_OFF,
    SIMORI_PERFORMANCE,
    SIMORI_CHANGE_VOICE,
    SIMORI_CHANGE_VELOCITY,
    SIMORI_CHANGE_LOOP_SPEED,
    SIMORI_CHANGE_LOOP_POINT,
    SIMORI_CHANGE_LAYER,
    SIMORI_SAVE_CONFIG,
    SIMORI_LOAD_CONFIG,
    SIMORI_MASTER_SLAVE
}