/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Simori_On_V2
import SimoriState

class App {
    val greeting: String
        get() {
            return "Hello Matt."
        }
}

fun main(args: Array<String>) {
    val s : SimoriState = SimoriState("hi")
    println(s.dummy)
}
