/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Simori_On_V2

class App {
    val greeting: String
        get() {
            return "Hello Matt."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
